config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
  end
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:index, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  profile_picture        :string
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :posts, dependent: :destroy
  has_many :sent_requests, class_name: 'FriendRequest', foreign_key: 'sender_id', dependent: :destroy
  has_many :received_requests, class_name: 'FriendRequest', foreign_key: 'recipient_id', dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
  mount_uploader :profile_picture, ProfilePictureUploader

  validates_presence_of :name

  scope :not_including, ->(user) { where.not(id: user.id) }
  scope :friends_of, ->(user) { where(id: Friendship.where(user: user).pluck(:friend_id)) }

  after_create :send_registration_email

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.name = provider_data.info.name
      user.remote_profile_picture_url = provider_data.info.image
      user.password = Devise.friendly_token[0, 20]
    end
  end

  private

  def send_registration_email
    RegistrationMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
      redirect_to new_user_registration_path
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
    redirect_to new_user_registration_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    # RegistrationMailer.with(user: @user).welcome_email.deliver_now if @user.persisted?
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:friends, :sent_requests).not_including(current_user)
  end

  def show
    @user = User.includes(:friends, :posts, :sent_requests).find(params[:id])    
  end
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<p class="title is-5">Catalog</p>
<div class="columns is-multiline">
  <% @users.each do |user| %>
    <div class="column is-one-third-desktop is-one-half-tablet">
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= user.name %></p>
              <p class="subtitle is-6">
                <% if current_user.friends.include?(user) %>
                  <span class="tag is-success">Friend</span>
                <% else %>
                  <span class="tag is-light">No relationship</span>
                <% end %>
              </p>
            </div>
          </div>
    
        </div>
        <div class="card-footer">
          <div class="card-footer-item">
            <%= link_to 'View profile', user_path(user) %>
          </div>
            <% unless current_user.friends.include?(user) %>
          <div class="card-footer-item">
              <% if current_user.sent_requests.find_by(recipient: user) %>
                <%= form_tag friend_request_path(current_user.sent_requests.find_by(recipient: user)), method: :delete do %>
                  <%= hidden_field_tag :friend_request_id, current_user.sent_requests.find_by(recipient: user).id %>
                  <%= submit_tag 'Cancel friend request', class: 'button is-danger is-light is-small' %>
                <% end %>
              <% else %>
                <%= form_tag friend_requests_path, method: :post do %>
                  <%= hidden_field_tag :recipient_id, user.id %>
                  <%= submit_tag 'Send friend request', class: 'button is-success is-light is-small' %>
                <% end %>
              <% end %>
          </div>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <%= image_tag @user.profile_picture_url(:thumb).to_s %>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= @user.name %></p>
        <p class="subtitle is-6">joined <%= time_ago_in_words(@user.created_at) %> ago
          <% unless current_user == @user %>
            <% if current_user.friends.include?(@user) %>
              <span class="tag is-success">Friend</span>
            <% else %>
              <span class="tag is-light">No relationship</span>
            <% end %>
          <% end %>
        </p>
        <%= link_to pluralize(@user.friends.size, 'friend'), friendships_path %>
      </div>
    </div>

  </div>
  <% unless current_user == @user %>
    <div class="card-footer">
      <% unless current_user.friends.include?(@user) %>
        <div class="card-footer-item">
          <% if current_user.sent_requests.find_by(recipient: @user) %>
            <%= form_tag friend_request_path(current_user.sent_requests.find_by(recipient: @user)), method: :delete do %>
              <%= hidden_field_tag :friend_request_id, current_user.sent_requests.find_by(recipient: @user).id %>
              <%= submit_tag 'Cancel friend request', class: 'button is-danger is-light is-small' %>
            <% end %>
          <% else %>
            <%= form_tag friend_requests_path, method: :post do %>
              <%= hidden_field_tag :recipient_id, @user.id %>
              <%= submit_tag 'Send friend request', class: 'button is-success is-light is-small' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<section class="section">
  <h2 class="title is-5">Feed (<%= pluralize(@user.posts.size, 'post') %>)</h2>
  <% @user.posts.each do |post| %>
    <div class="box">
      <%= render "posts/post", post: post %>
    </div>
  <%end %>
</section>