config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
  end
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:index, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_friends_sidebar.html.erb
<aside class="menu">
  <p class="menu-label">Friends</p>
  <ul class="menu-list">
    <% current_user.friends.each do |friend| %>
      <li><%= link_to friend.name, user_path(friend), class: 'has-text-link' %></li>
    <% end %>
  </ul>
</aside>

app/views/shared/_navbar.html.erb
<nav class="navbar has-background-success" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to posts_path, class: 'navbar-item' do %>
      <%= image_tag 'spaceship.png' %>Cosmos
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navMenu" class="navbar-menu">
    <% if user_signed_in? %>
      <%= render "shared/signed_in" %>
    <% else %>
      <%= render "shared/signed_out" %>
    <% end %>
  </div>
</nav>

app/views/shared/_quick_actions.html.erb
<aside class="menu">
  <p class="menu-label">Quick actions</p>
  <ul class="menu-list">
    <li><%= link_to 'Post something', new_post_path, class: 'has-text-link' %></li>
    <li><%= link_to 'Find new friends', users_path, class: 'has-text-link' %></li>
    <li><%= link_to 'Your friends', friendships_path, class: 'has-text-link' %></li>
    <li><%= link_to 'Your profile', user_path(current_user), class: 'has-text-link' %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'has-text-link' %></li>
  </ul>
</aside>

app/views/shared/_signed_in.html.erb
<div class="navbar-start">

  <%= link_to 'Post something', new_post_path, class: 'navbar-item showable' %>
  <%= link_to 'User catalog', users_path, class: 'navbar-item showable' %>

  <%= link_to 'Friends', friendships_path, class: 'navbar-item showable' %>
  <%= link_to 'Profile', user_path(current_user), class: 'navbar-item showable' %>

  <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-item showable' %>
  
</div>

<div class="navbar-end">
<div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link">
      Notifications
    </a>

    <div class="navbar-dropdown">
      <% if current_user.received_requests.any? %>
        <% current_user.received_requests.each do |request| %>
          <div class="navbar-item">
            <div class="box">
              Friend request from<br>
              <strong><%= request.sender.name %></strong><br>
              <div class="level is-mobile">
                <div class="level-left">
                  <div class="level-item">
                    <%= form_tag friendships_path do %>
                      <%= hidden_field_tag :friend_request_id, request.id %>
                      <%= hidden_field_tag :friend_id, request.sender.id %>
                      <%= submit_tag 'Add friend', class: 'button is-success is-small' %>
                    <% end %>
                  </div>
                  <div class="level-item">
                    <%= form_tag friend_request_path(request.id), method: :delete do %>
                      <%= submit_tag 'Decline request', class: 'button is-danger is-small' %>
                    <% end %>
                  </div>
                </div>
                <div class="level-right"></div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="navbar-item">
          *No new notifications*
        </p>
      <% end %>
    </div>
  </div>
  <div class="navbar-item">
    <div class="buttons">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete,
                              class: 'button' %>
    </div>
  </div>
</div>

app/views/shared/_signed_out.html.erb
<div class="navbar-start">
  <a class="navbar-item">
    About
  </a>
</div>

<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons">
      <%= link_to 'Sign up', new_user_registration_path, class: 'button is-light' %>
      <%= link_to 'Log in', new_user_session_path, class: 'button is-success is-light' %>
    </div>
  </div>
</div>