config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
  end
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:index, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_presence_of :content

  scope :recent, -> { order(created_at: :desc) }

  def liked_by?(user)
    likes.find_by(user: user).present?
  end

  def feed_author_name(logged_in_user)
    author == logged_in_user ? 'You' : author.name
  end

  def auto_like
    self.likes.build(user: self.author) 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author, :likes, :comments).recent
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = Post.new(post_params)

    @post.auto_like if posted_with_auto_like?

    if @post.save
      flash[:notice] = 'Succesfully posted to feed.'
      redirect_to posts_path
    else
      flash[:alert] = 'Fix some things before posting.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :content)
  end

  def posted_with_auto_like?
    params[:post][:like_own_post] == '1'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_heading.html.erb
<strong><%= link_to "#{post.feed_author_name(current_user)}", user_path(post.author) %></strong><small>&nbsp;· <%= time_ago_in_words(post.created_at) %> ago · <%= link_to "#{pluralize(post.likes.size, 'like')}", post_likes_path(post) %> · <%= link_to "#{pluralize(post.comments.size, 'comment')}", post_comments_path(post) %></small>

app/views/posts/_post.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag post.author.profile_picture_url(:thumb).to_s %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <%= render "posts/heading", post: post %>

      <% if post.liked_by?(current_user) %>
        <%= form_tag post_like_path(post, post.likes.find_by(user: current_user)), method: :delete,
                     style: 'display: inline !important;' do %>
          <%= submit_tag 'Remove like', class: 'button is-danger is-light is-small' %>
        <% end %>
      <% else %>
        <%= form_tag post_likes_path(post), method: :post, style: 'display: inline !important;' do %>
          <%= hidden_field_tag :post_id, post.id %> 
          <%= submit_tag 'Like post', class: 'button is-success is-light is-small' %>
        <% end %>
      <% end %>
      <br>
      <%= post.content %>
    </div>
    <%= form_tag post_comments_path(post), method: :post do %>
      <%= hidden_field_tag 'comment[post_id]', post.id %>
      <%= text_area_tag 'comment[content]', nil, placeholder: 'Say something about it...', class: 'textarea', rows: 1, required: 'required' %>
      <div class="level is-mobile" style="padding: 10px 0;">
        <div class="level-left">
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= submit_tag 'Comment', class: 'button is-success is-light is-small' %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</article>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="box">
    <%= render "posts/post", post: post %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="box">
  <p class="title has-text-centered is-5">Create post</p>
  <div class="errors content">
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>  
        <% end %>
      </ul>
    <% end %>
  </div>
  <%= form_with model: @post do |f| %>
    <%= f.hidden_field :user_id %>
    <article class="media">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= image_tag current_user.profile_picture_url(:thumb).to_s %>
        </p>
      </figure>
      <div class="media-content">
        <div class="field">
          <p class="control">
            <%= f.text_area :content, class: 'textarea', placeholder: "Tell us what's on your mind..." %>
          </p>
        </div>
        <nav class="level">
          <div class="level-left">
            <div class="level-item">
              <%= f.submit 'Post to feed', class: 'button is-link' %>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
                <%= f.label class: 'checkbox' do %>
                  Gift yourself the first like ;)
                  <%= f.check_box :like_own_post %>
                <% end %>
            </div>
          </div>
        </nav>
      </div>
    </article>
  <% end %>
</div>